import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const sourceFiles = [
  "src/constants.js",
  "src/utils.js",
  "src/storage.js",
  "src/styles.js",
  "src/template.js",
  "src/app.js",
  "src/index.js",
];

const indentBlock = (source) =>
  source
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");

const chunks = await Promise.all(
  sourceFiles.map(async (file) => {
    const absolutePath = path.join(root, file);
    const source = await readFile(absolutePath, "utf8");
    return `// ${file}\n${source.trim()}`;
  })
);

const bundle = `/* eslint-disable */
/* Generated by scripts/build.mjs. Edit files in src/ and rebuild. */
(() => {
${chunks.map(indentBlock).join("\n\n")}
})();
`;

await mkdir(path.join(root, "dist"), { recursive: true });
await writeFile(path.join(root, "dist", "wavez-tools.js"), bundle, "utf8");

console.log(`Built dist/wavez-tools.js from ${sourceFiles.length} source files.`);
